name: Deploy Nuxt to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: yarn install

      - name: Generate static site
        run: yarn generate

      - name: Copy dist to docs
        run: |
          mkdir -p docs
          cp -r dist/* docs/
          touch docs/.nojekyll
          echo "dhunganapradip.com.np" > docs/CNAME

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add docs
          git commit -m "Deploy static site to docs"
          git push origin main